### ISSUE TITLE
unable to shoot moon in last cutscene

### ISSUE THREAD

**Issue by Goruku123456** [URAKOLOUY5/gp2#45] opened 2024-10-29 08:55 UTC

**Comment by URAKOLOUY5** [comment] 2024-10-29 09:00
Duplicate of #34

**Closed** 2024-10-29 09:00 UTC

**Comment by Goruku123456** [comment] 2024-10-29 09:02
My bad about the duplicates, I didn’t see the second page. Sorry

**Comment by URAKOLOUY5** [comment] 2024-10-29 09:03
That's fine, just precheck if there any related issues to your problem

**Comment by Goruku123456** [comment] 2024-10-29 09:05
Thanks, I will. Great mod btw.
