### ISSUE TITLE
Wheatley goes off rail in some test chambers.

### ISSUE THREAD

**Issue by skittleguy** [URAKOLOUY5/gp2#49] opened 2024-12-14 06:35 UTC
One example is in the test chamber sp_a2_bts4 in the middle while he talks to the player and at the end when he tries to go off map.
![Screenshot 2024-12-14 052902](https://github.com/user-attachments/assets/1c113242-1fb8-4c2a-80c7-a4c2950e348f)
![Screenshot 2024-12-14 054112](https://github.com/user-attachments/assets/e4a1aa1e-5fca-4701-8dd2-b2ad75f37b7d)
![Screenshot 2024-12-14 073051](https://github.com/user-attachments/assets/6235d585-ffc6-48a3-9b6e-51ac32a4d0a5)
![Screenshot 2024-12-14 073123](https://github.com/user-attachments/assets/c1c59fe1-9d5c-4572-8c6b-be5926b3f074)

**Comment by URAKOLOUY5** [comment] 2024-12-14 12:57
Duplicate of #28

**Closed** 2024-12-14 12:57 UTC
